(dp1
S'files'
p2
(dp3
S'input'
p4
(lp5
sS'output'
p6
(lp7
(dp8
S'argName'
p9
S'outputEVNTFile'
p10
sS'dataset'
p11
NsS'type'
p12
S'EVNT'
p13
sS'subFiles'
p14
(lp15
(dp16
S'run_number'
p17
NsS'name'
p18
S'test2.EVNT.root'
p19
sS'beam_energy'
p20
NsS'file_type'
p21
NsS'AODFixVersion'
p22
NsS'lumi_block'
p23
NsS'geometry'
p24
NsS'beam_type'
p25
NsS'file_guid'
p26
NsS'file_size'
p27
NsS'conditions_tag'
p28
NsS'integrity'
p29
NsS'nentries'
p30
NsasassS'exitMsg'
p31
S'Non-zero return code from generate (8); Logfile error in log.generate: "RuntimeError: Error in MadGraph generation"'
p32
sS'exitMsgExtra'
p33
S''
sS'exitCode'
p34
I65
sS'resource'
p35
(dp36
S'machine'
p37
(dp38
S'node'
p39
S'at3i00.hep.upenn.edu'
p40
sS'linux_distribution'
p41
(S'Scientific Linux'
S'6.6'
S'Carbon'
tp42
sS'platform'
p43
S'Linux-2.6.32-504.3.3.el6.x86_64-x86_64-with-redhat-6.6-Carbon'
p44
sS'cpu_family'
p45
S'6'
sS'model'
p46
S'26'
p47
sS'model_name'
p48
S'Intel(R) Xeon(R) CPU           X5570  @ 2.93GHz'
p49
ssS'transform'
p50
(dp51
S'externalCpuTime'
p52
I0
sS'cpuTime'
p53
I1
sS'wallTime'
p54
I4
ssS'executor'
p55
(dp56
S'generate'
p57
(dp58
g53
I2
sg54
I3
ssssg18
S'Generate_tf'
p59
sS'created'
p60
S'2015-06-10T16:09:22'
p61
sS'cmdLine'
p62
S"'/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/19.2.4/AtlasProduction/19.2.4.2/InstallArea/share/bin/Generate_tf.py' '--ecmEnergy' '13000' '--runNumber' '406004' '--firstEvent' '0' '--maxEvents' '10' '--randomSeed' '0' '--jobConfig' 'MC15JobOptions/share/DSID406xxx/MC15.406004.MadGraphPythia8EvtGen_A14NNPDF23LO_C1N2_WZ_400_100_3lep.py' '--outputEVNTFile' 'test2.EVNT.root'"
p63
sS'exitAcronym'
p64
S'TRF_EXEC_FAIL'
p65
sg55
(lp66
(dp67
S'metaData'
p68
(dp69
sg18
g57
sS'asetup'
p70
NsS'exeConfig'
p71
(dp72
S'outputs'
p73
(lp74
S'EVNT'
p75
asS'script'
p76
S'athena.py'
p77
sS'substep'
p78
NssS'statusOK'
p79
I00
sS'rc'
p80
I8
sS'validation'
p81
I00
sS'errMsg'
p82
S'Non-zero return code from generate (8)'
p83
sS'logfileReport'
p84
(dp85
S'details'
p86
(dp87
S'FATAL'
p88
(lp89
(dp90
S'count'
p91
I1
sS'message'
p92
S'RuntimeError: Error in MadGraph generation'
p93
sS'firstLine'
p94
I37
sasS'ERROR'
p95
(lp96
(dp97
g91
I1
sg92
S'Py:MadGraphUtils    ERROR Bad idea to generate 20.0 events.  MadGraph wont complain, but the job will never end.  Bailing out now.'
p98
sg94
I26
sassS'countSummary'
p99
(dp100
S'INFO'
p101
I21
sS'IGNORED'
p102
I0
sS'VERBOSE'
p103
I0
sS'UNKNOWN'
p104
I3
sS'WARNING'
p105
I2
sS'CRITICAL'
p106
I0
sg95
I1
sS'DEBUG'
p107
I0
sg88
I1
sssasS'reportVersion'
p108
S'1.0.1'
p109
sS'argValues'
p110
(dp111
S'randomSeed'
p112
(dp113
S'all'
p114
I0
ssS'printEvts'
p115
I5
sS'runNumber'
p116
I406004
sS'ecmEnergy'
p117
F13000
sS'maxEvents'
p118
(dp119
g114
I10
ssS'jobConfig'
p120
(dp121
g114
(lp122
S'MC15JobOptions/share/DSID406xxx/MC15.406004.MadGraphPythia8EvtGen_A14NNPDF23LO_C1N2_WZ_400_100_3lep.py'
p123
assS'firstEvent'
p124
I0
sS'athenaopts'
p125
(lp126
S'--preloadlib=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/19.2.4/sw/IntelSoftware/linux/x86_64/xe2013/composer_xe_2013.3.163/compiler/lib/intel64/libintlc.so.5:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/19.2.4/sw/IntelSoftware/linux/x86_64/xe2013/composer_xe_2013.3.163/compiler/lib/intel64/libimf.so'
p127
asg10
(lp128
g19
ass.